import {
  LucideAirVent,
  LucideArrowLeft,
  LucideBrickWall,
  LucideCheck,
  LucideChevronRight,
  LucideClock,
  LucideDroplets,
  LucideHammer,
  LucideHandHelping,
  LucideLayoutGrid,
  LucideLoaderCircle,
  LucideLogIn,
  LucideLogOut,
  LucideMapPin,
  LucideMessageCircle,
  LucideMessageSquareText,
  LucideMic,
  LucideMicOff,
  LucidePaintRoller,
  LucidePlus,
  LucideSearch,
  LucideSearchX,
  LucideShieldCheck,
  LucideSmartphone,
  LucideSparkles,
  LucideSprout,
  LucideStar,
  LucideStarHalf,
  LucideUserRound,
  LucideX,
  LucideZap,
  provideLucideIcons,
} from '@lucide/angular';

/**
 * Ícones registrados por nome para uso com `<svg lucideIcon="nome">`.
 * Ao usar um ícone novo, adicione-o aqui.
 */
export function provideAppIcons() {
  return provideLucideIcons(
    LucideAirVent,
    LucideArrowLeft,
    LucideBrickWall,
    LucideCheck,
    LucideChevronRight,
    LucideClock,
    LucideDroplets,
    LucideHammer,
    LucideHandHelping,
    LucideLayoutGrid,
    LucideLoaderCircle,
    LucideLogIn,
    LucideLogOut,
    LucideMapPin,
    LucideMessageCircle,
    LucideMessageSquareText,
    LucideMic,
    LucideMicOff,
    LucidePaintRoller,
    LucidePlus,
    LucideSearch,
    LucideSearchX,
    LucideShieldCheck,
    LucideSmartphone,
    LucideSparkles,
    LucideSprout,
    LucideStar,
    LucideStarHalf,
    LucideUserRound,
    LucideX,
    LucideZap,
  );
}
