// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bendita_ajuda_backend.Data;

#nullable disable

namespace bendita_ajuda_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007185849_BuscasSemResultado")]
    partial class BuscasSemResultado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("PrestadoresServicos", b =>
                {
                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ServicoId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("PrestadorId", "ServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("PrestadoresServicos");
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.BuscaNaoEntendida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("PrimeiraVez")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UltimaVez")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Texto")
                        .IsUnique();

                    b.ToTable("BuscasNaoEntendidas", (string)null);
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.BuscaSemPrestador", b =>
                {
                    b.Property<string>("ServicoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaVez")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ServicoId", "Cidade", "Uf");

                    b.ToTable("BuscasSemPrestador", (string)null);
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.CodigoVerificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Celular", "CriadoEm");

                    b.ToTable("CodigosVerificacao", (string)null);
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.Prestador", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<bool>("Visivel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Uf", "Cidade", "Bairro");

                    b.ToTable("Prestadores", (string)null);
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.Servico", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomePlural")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("PalavrasChave")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Servicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "eletricista",
                            Nome = "Eletricista",
                            NomePlural = "Eletricistas",
                            Ordem = 1,
                            PalavrasChave = "tecnico eletrico, tecnico em eletrica, eletrotecnico, eletrica, eletrico, luz, tomada, chuveiro, disjuntor, fio, fiacao, lampada, interruptor, curto, energia, queimou, choque, quadro de luz"
                        },
                        new
                        {
                            Id = "encanador",
                            Nome = "Encanador",
                            NomePlural = "Encanadores",
                            Ordem = 2,
                            PalavrasChave = "bombeiro hidraulico, hidraulica, agua, pia, vazamento, vazando, vaza, cano, torneira, descarga, privada, vaso sanitario, entupido, entupida, entupiu, esgoto, caixa d agua, registro, ralo"
                        },
                        new
                        {
                            Id = "faxina",
                            Nome = "Faxina",
                            NomePlural = "Profissionais de faxina",
                            Ordem = 3,
                            PalavrasChave = "faxineira, faxineiro, diarista, limpeza, limpar, passar roupa, lavar, sujeira"
                        },
                        new
                        {
                            Id = "pedreiro",
                            Nome = "Pedreiro",
                            NomePlural = "Pedreiros",
                            Ordem = 4,
                            PalavrasChave = "obra, reforma, parede, piso, reboco, muro, telhado, goteira, rachadura, azulejo, cimento, construcao, calcada, laje"
                        },
                        new
                        {
                            Id = "pintor",
                            Nome = "Pintor",
                            NomePlural = "Pintores",
                            Ordem = 5,
                            PalavrasChave = "pintura, pintar, tinta, descascando, mofo, textura, grafiato, verniz"
                        },
                        new
                        {
                            Id = "jardineiro",
                            Nome = "Jardineiro",
                            NomePlural = "Jardineiros",
                            Ordem = 6,
                            PalavrasChave = "jardinagem, jardim, grama, planta, plantas, poda, podar, arvore, mato, quintal, rocar, horta"
                        },
                        new
                        {
                            Id = "montador-de-moveis",
                            Nome = "Montador de móveis",
                            NomePlural = "Montadores de móveis",
                            Ordem = 7,
                            PalavrasChave = "montar, montagem, movel, moveis, guarda roupa, armario, cama, estante, desmontar, prateleira, rack, mudanca"
                        },
                        new
                        {
                            Id = "tecnico-ar-condicionado",
                            Nome = "Técnico de ar-condicionado",
                            NomePlural = "Técnicos de ar-condicionado",
                            Ordem = 8,
                            PalavrasChave = "ar, ar condicionado, split, climatizacao, nao gela, gelando, refrigeracao"
                        });
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.ServicoSugerido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("PrestadorId");

                    b.ToTable("ServicosSugeridos", (string)null);
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("CelularConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PrestadoresServicos", b =>
                {
                    b.HasOne("bendita_ajuda_backend.Data.Entidades.Prestador", null)
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bendita_ajuda_backend.Data.Entidades.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.Prestador", b =>
                {
                    b.HasOne("bendita_ajuda_backend.Data.Entidades.Usuario", "Usuario")
                        .WithOne("Prestador")
                        .HasForeignKey("bendita_ajuda_backend.Data.Entidades.Prestador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.ServicoSugerido", b =>
                {
                    b.HasOne("bendita_ajuda_backend.Data.Entidades.Prestador", "Prestador")
                        .WithMany("Sugestoes")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.Prestador", b =>
                {
                    b.Navigation("Sugestoes");
                });

            modelBuilder.Entity("bendita_ajuda_backend.Data.Entidades.Usuario", b =>
                {
                    b.Navigation("Prestador");
                });
#pragma warning restore 612, 618
        }
    }
}
